---
resources:
- name: repo
  type: git
  source:
    uri: https://github.com/dolph/git-ready.git
    branch: master

jobs:
- name: testing
  plan:
  - get: repo
    trigger: true
  - task: test
    config:
        platform: linux
        image_resource:
            type: docker-image
            source:
                repository: ubuntu
                tag: "latest"
        inputs:
        - name: repo
        run:
            path: repo/test.sh
