---
resources:
- name: repo
  type: git
  source:
    uri: https://github.com/dolph/git-ready.git
    branch: master

jobs:
- name: test
  plan:
  - get: repo
    trigger: true
  - task: smoke-test
    config:
        platform: linux
        image_resource:
            type: docker-image
            source:
                repository: ubuntu
                tag: "latest"
        inputs:
        - name: repo
        run:
            path: repo/ci/test
- name: release
  plan:
  - get: repo
    passed: [test]
    trigger: true
  - task: upload-to-pypi
    config:
        platform: linux
        image_resource:
            type: docker-image
            source:
                repository: ubuntu
                tag: "latest"
        inputs:
        - name: repo
        run:
            path: repo/ci/release {{pypi-username}} {{pypi-password}}
