#!/bin/bash
set -e

# Absolute path to this script, e.g. /home/user/bin/foo.sh
SCRIPT=$(readlink -f "$0")
# Absolute path this script is in, thus /home/user/bin
SCRIPTPATH=$(dirname "$SCRIPT")

if [ ! -f $HOME/.pypirc ] ; then
    echo 'PyPi RC file does not exist, attempting to create one...'
    echo '[distutils]' > $HOME/.pypirc
    echo 'index-servers = ' >> $HOME/.pypirc
    echo '    pypi' >> $HOME/.pypirc
    echo '' >> $HOME/.pypirc
    echo '[pypi]' >> $HOME/.pypirc
    echo "username: ${1}" >> $HOME/.pypirc
    echo "password: ${2}" >> $HOME/.pypirc
fi

cd $SCRIPTPATH/../

# Build a source distribution.
python setup.py sdist

# Check if we need to upload a new version before doing so.
VERSION=`python setup.py --version`
curl -I https://pypi.python.org/pypi/git-ready/$VERSION | grep "HTTP/1.1 200 OK" || python setup.py upload
