#!/bin/bash
set -e

# Absolute path to this script, e.g. /home/user/bin/foo.sh
SCRIPT=$(readlink -f "$0")
# Absolute path this script is in, thus /home/user/bin
SCRIPTPATH=$(dirname "$SCRIPT")

if [ ! -f $HOME/.pypirc ] ; then
    echo 'PyPi RC file does not exist, attempting to create one...'
    echo '[pypi]' > $HOME/.pypirc
    echo "username: ${1}" >> $HOME/.pypirc
    echo "password: ${2}" >> $HOME/.pypirc
fi
echo $HOME/.pypirc
cat $HOME/.pypirc

cd $SCRIPTPATH/../
python setup.py sdist upload
