#!/bin/bash
set -e

# Absolute path to this script, e.g. /home/user/bin/foo.sh
SCRIPT=$(readlink -f "$0")
# Absolute path this script is in, thus /home/user/bin
SCRIPTPATH=$(dirname "$SCRIPT")

# Install test dependencies
apt-get update
apt-get install git -y

# Setup git-ready
cd $SCRIPTPATH/../
pip install -e .

# Prepare to test against a subject repo.
mkdir -p $SCRIPTPATH/ci/tmp/
git clone --depth=1 https://github.com/openstack/nova.git $SCRIPTPATH/ci/tmp/nova
cd $SCRIPTPATH/ci/tmp/nova

# Test with no branch specified.
git ready

# Test with a particular branch specified.
git ready master
